# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'PR welcome'
description: 'Thanks for your contribution. 😅 But I refuse.'
author: 'xrkffgg'

branding:
  # https://feathericons.com/
  # e.g. https://haya14busa.github.io/github-action-brandings/
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  refuse-issue-label:
    description: Don’t come when there is this label
  need-creator-authority:
    description: Author rights
  comment:
    description: Refuse comment
  close:
    description: If refuse close

runs:
  using: 'node12'
  main: 'dist/index.js'
