name: PR Welcome

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/pr-welcome@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          refuse-issue-label: 'bug'
          need-creator-authority: 'write'
          comment: |
            HI
          emoji: '+1, -1, heart'
          close: true
